import re
from xml.sax.saxutils import escape, quoteattr

from src.model import Solution, SolutionEvent, SolutionGroup

_SOLUTION_GROUPS_RE = re.compile(r"<SolutionGroups>.*?</SolutionGroups>", re.DOTALL)
_ARCHIVE_CLOSE_RE = re.compile(r"</HighSchoolTimetableArchive>")


def _render_solution_event(se: SolutionEvent) -> str:
    parts = [f"<Event Reference={quoteattr(se.event_ref)}>"]
    if se.duration is not None:
        parts.append(f"<Duration>{se.duration}</Duration>")
    if se.time_ref is not None:
        parts.append(f"<Time Reference={quoteattr(se.time_ref)}/>")
    if se.resources:
        parts.append("<Resources>")
        for r in se.resources:
            parts.append(
                f"<Resource Reference={quoteattr(r.resource_ref)}>"
                f"<Role>{escape(r.role)}</Role></Resource>"
            )
        parts.append("</Resources>")
    parts.append("</Event>")
    return "".join(parts)


def render_solution(solution: Solution) -> str:
    events_xml = "".join(_render_solution_event(se) for se in solution.events)
    return (
        f"<Solution Reference={quoteattr(solution.instance_ref)}>"
        f"<Events>{events_xml}</Events>"
        f"</Solution>"
    )


def render_solution_group(group: SolutionGroup) -> str:
    # <MetaData><Contributor/><Date/><Description/></MetaData>, in this
    # order, is mandatory before <Solution> -- HSEval's validator rejects a
    # SolutionGroup missing any of these ("child <MetaData>/<Date> missing
    # or out of order"), confirmed against the real endpoint.
    solutions_xml = "".join(render_solution(s) for s in group.solutions)
    return (
        f"<SolutionGroup Id={quoteattr(group.id)}>"
        f"<MetaData><Contributor>src</Contributor>"
        f"<Date>01-01-2026</Date>"
        f"<Description>Generated by src</Description></MetaData>"
        f"{solutions_xml}"
        f"</SolutionGroup>"
    )


def extract_instance_archive(archive_xml: str, instance_id: str) -> str:
    """Slices a single <Instance> out of a multi-instance archive (like the
    full XHSTT-2014.xml, 25 instances in one file) and wraps it in a
    minimal, self-contained archive -- so a solution for just that
    instance can be written and submitted to HSEval without dragging the
    other instances along."""
    match = re.search(
        rf"<Instance Id={quoteattr(instance_id)}[^>]*>.*?</Instance>",
        archive_xml,
        re.DOTALL,
    )
    if match is None:
        raise ValueError(f"Missing <Instance Id={instance_id!r}> in archive")
    return (
        "<HighSchoolTimetableArchive><Instances>"
        f"{match.group()}"
        "</Instances></HighSchoolTimetableArchive>"
    )


def render_archive_with_solution_groups(
    archive_xml: str, groups: list[SolutionGroup]
) -> str:
    """Returns `archive_xml` with its <SolutionGroups> section replaced by
    `groups` (added if absent) -- the shape HSEval's op=report endpoint
    expects for evaluating solver-produced solutions against a real
    instance."""
    groups_xml = (
        "<SolutionGroups>"
        + "".join(render_solution_group(g) for g in groups)
        + "</SolutionGroups>"
    )

    if _SOLUTION_GROUPS_RE.search(archive_xml):
        return _SOLUTION_GROUPS_RE.sub(groups_xml, archive_xml, count=1)
    return _ARCHIVE_CLOSE_RE.sub(
        groups_xml + "</HighSchoolTimetableArchive>", archive_xml, count=1
    )
